#!/bin/bash

# Generate C++ source file containing ROM data as byte arrays
# Usage: generate_roms.sh <rom_directory> <output_file>

ROM_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$ROM_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <rom_directory> <output_file>"
    exit 1
fi

# Start the output file
cat > "$OUTPUT_FILE" << 'EOF'
// Auto-generated ROM data - DO NOT EDIT
// Generated by generate_roms.sh

#include <cstdint>
#include <cstddef>

namespace roms {

EOF

# Function to convert a binary file to a C array
generate_array() {
    local file="$1"
    local name="$2"

    if [ ! -f "$file" ]; then
        echo "// ROM file not found: $file" >> "$OUTPUT_FILE"
        echo "const uint8_t ${name}[] = {};" >> "$OUTPUT_FILE"
        echo "const size_t ${name}_SIZE = 0;" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        return
    fi

    local size=$(wc -c < "$file" | tr -d ' ')

    echo "// $(basename "$file")" >> "$OUTPUT_FILE"
    echo "const uint8_t ${name}[] = {" >> "$OUTPUT_FILE"

    xxd -i < "$file" | sed 's/^/    /' >> "$OUTPUT_FILE"

    echo "};" >> "$OUTPUT_FILE"
    echo "const size_t ${name}_SIZE = $size;" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Generate arrays for each ROM
# Prefer combined ROM if available
if [ -f "$ROM_DIR/342-0349-B-C0-FF.bin" ]; then
    generate_array "$ROM_DIR/342-0349-B-C0-FF.bin" "ROM_SYSTEM"
elif [ -f "$ROM_DIR/342-0135-A-CD.bin" ] && [ -f "$ROM_DIR/342-0134-A-EF.bin" ]; then
    # Fallback to separate CD/EF ROMs - combine them
    generate_array "$ROM_DIR/342-0135-A-CD.bin" "ROM_CD"
    generate_array "$ROM_DIR/342-0134-A-EF.bin" "ROM_EF"
fi

generate_array "$ROM_DIR/342-0273-A-US-UK.bin" "ROM_CHAR"

# Apple II Plus. These are optional: when the files are absent the arrays are
# emitted empty with size 0, the II+ profile reports no ROM, and the machine is
# offered but cannot be started. The //e is unaffected either way.
#
# A II+ motherboard carries six 2KB ROMs in sockets D0 to F8, covering
# $D000-$FFFF: five of Applesoft and the Autostart monitor at $F800. They are
# concatenated in address order into one 12KB image. A single pre-combined
# apple2plus.rom is accepted instead.
II_PLUS_PARTS=(341-0011.bin 341-0012.bin 341-0013.bin \
               341-0014.bin 341-0015.bin 341-0020.bin)

have_all_parts=1
for part in "${II_PLUS_PARTS[@]}"; do
    [ -f "$ROM_DIR/$part" ] || have_all_parts=0
done

if [ "$have_all_parts" = "1" ]; then
    combined="$ROM_DIR/.iiplus-combined.tmp"
    : > "$combined"
    for part in "${II_PLUS_PARTS[@]}"; do
        cat "$ROM_DIR/$part" >> "$combined"
    done
    generate_array "$combined" "ROM_SYSTEM_II_PLUS"
    rm -f "$combined"
else
    generate_array "$ROM_DIR/apple2plus.rom" "ROM_SYSTEM_II_PLUS"
fi

generate_array "$ROM_DIR/341-0036.bin" "ROM_CHAR_II_PLUS"

# Apple //c. Optional in exactly the way the II+ set is: absent files give
# empty arrays, the profile reports no ROM, and the machine is listed but
# cannot be started.
#
# The original //c (ROM 255) carries one 16KB ROM covering $C000-$FFFF, and a
# 4KB character generator. A single pre-combined apple2c.rom is accepted for
# the first, as apple2plus.rom is above. Later //c ROMs (342-0033-A is ROM 0,
# 341-0445-A/B are ROMs 3 and 4) are 32KB and bank-switched, which is a
# different machine from the one the profile describes, so they are not taken.
if [ -f "$ROM_DIR/342-0272-A.bin" ]; then
    generate_array "$ROM_DIR/342-0272-A.bin" "ROM_SYSTEM_IIC"
else
    generate_array "$ROM_DIR/apple2c.rom" "ROM_SYSTEM_IIC"
fi

# The character generator is the enhanced //e's part, which some dumps label
# with its 341- number instead.
if [ -f "$ROM_DIR/342-0265-A.bin" ]; then
    generate_array "$ROM_DIR/342-0265-A.bin" "ROM_CHAR_IIC"
else
    generate_array "$ROM_DIR/341-0265-A.bin" "ROM_CHAR_IIC"
fi
generate_array "$ROM_DIR/341-0027.bin" "ROM_DISK2"
generate_array "$ROM_DIR/Thunderclock Plus ROM.bin" "ROM_THUNDERCLOCK"
generate_array "$ROM_DIR/Apple Mouse Interface Card ROM - 342-0270-C.bin" "ROM_MOUSE"
generate_array "$ROM_DIR/Super Serial Card ROM - 341-0065-A.bin" "ROM_SSC"
generate_array "$ROM_DIR/Apple Parallel Interface Card ROM - 341-0057.bin" "ROM_PARALLEL"

# Close namespace
echo "} // namespace roms" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
