#!/bin/bash

# Generate C++ source file containing ROM data as byte arrays
# Usage: generate_roms.sh <rom_directory> <output_file>

ROM_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$ROM_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <rom_directory> <output_file>"
    exit 1
fi

# Start the output file
cat > "$OUTPUT_FILE" << 'EOF'
// Auto-generated ROM data - DO NOT EDIT
// Generated by generate_roms.sh

#include <cstdint>
#include <cstddef>

namespace roms {

EOF

# Function to convert a binary file to a C array
generate_array() {
    local file="$1"
    local name="$2"

    if [ ! -f "$file" ]; then
        echo "// ROM file not found: $file" >> "$OUTPUT_FILE"
        echo "const uint8_t ${name}[] = {};" >> "$OUTPUT_FILE"
        echo "const size_t ${name}_SIZE = 0;" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        return
    fi

    local size=$(wc -c < "$file" | tr -d ' ')

    echo "// $(basename "$file")" >> "$OUTPUT_FILE"
    echo "const uint8_t ${name}[] = {" >> "$OUTPUT_FILE"

    xxd -i < "$file" | sed 's/^/    /' >> "$OUTPUT_FILE"

    echo "};" >> "$OUTPUT_FILE"
    echo "const size_t ${name}_SIZE = $size;" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Generate arrays for each ROM
# Prefer combined ROM if available
if [ -f "$ROM_DIR/342-0349-B-C0-FF.bin" ]; then
    generate_array "$ROM_DIR/342-0349-B-C0-FF.bin" "ROM_SYSTEM"
elif [ -f "$ROM_DIR/342-0135-A-CD.bin" ] && [ -f "$ROM_DIR/342-0134-A-EF.bin" ]; then
    # Fallback to separate CD/EF ROMs - combine them
    generate_array "$ROM_DIR/342-0135-A-CD.bin" "ROM_CD"
    generate_array "$ROM_DIR/342-0134-A-EF.bin" "ROM_EF"
fi

generate_array "$ROM_DIR/342-0273-A-US-UK.bin" "ROM_CHAR"
generate_array "$ROM_DIR/341-0027.bin" "ROM_DISK2"
generate_array "$ROM_DIR/Thunderclock Plus ROM.bin" "ROM_THUNDERCLOCK"
generate_array "$ROM_DIR/Apple Mouse Interface Card ROM - 342-0270-C.bin" "ROM_MOUSE"
generate_array "$ROM_DIR/Super Serial Card ROM - 341-0065-A.bin" "ROM_SSC"

# Close namespace
echo "} // namespace roms" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
