/*
 * audio-driver.js - Web Audio API driver for emulator audio and timing
 *
 * In Worker mode, audio samples are generated by the Worker and relayed
 * through this driver to the AudioWorklet. The driver no longer calls
 * WASM directly for sample generation.
 *
 * Written by
 *  Mike Daley <michael_daley@icloud.com>
 */

// Audio constants
import { VERSION } from '../config/version.js';

const SAMPLE_RATE = 48000;
const DEFAULT_VOLUME = 0.5;

export class AudioDriver {
  constructor(wasmModule) {
    this.wasmModule = wasmModule;
    this.audioContext = null;
    this.workletNode = null;
    this.gainNode = null;

    this.sampleRate = SAMPLE_RATE;
    this.running = false;
    this.muted = this.loadMuted();
    this.volume = this.loadVolume();
    this.speed = 1;

    // Fallback to ScriptProcessorNode if AudioWorklet not available
    this.useWorklet = typeof AudioWorkletNode !== "undefined";
    this.scriptProcessor = null;

    // Set by setSharedAudioBuffer() when SharedArrayBuffer is available.
    this.sharedAudioBuffer = null;

    // Called with true when the machine must be paced by something other than
    // audio, and false when audio has taken over. Wired to the Worker in main.js.
    this.onFreeRunChange = null;

    // Sync C++ audio state with saved JS settings (fire-and-forget via proxy)
    this.applyVolumeToEmulator();
  }

  /**
   * Push the current volume and mute state into the core.
   *
   * Called at construction, and again whenever the core has been rebuilt
   * underneath us — a machine switch constructs a new emulator, which knows
   * nothing of the volume the user set on the old one.
   */
  applyVolumeToEmulator() {
    this.wasmModule._setAudioVolume(this.volume);
    this.wasmModule._setAudioMuted(this.muted);
  }

  async start() {
    if (this.running) return;

    try {
      this.audioContext = new (window.AudioContext ||
        window.webkitAudioContext)({
        sampleRate: this.sampleRate,
      });

      if (this.audioContext.state === "suspended") {
        // No gesture yet, so audio cannot start and nothing will ask the Worker
        // for samples. Pace the machine from a timer meanwhile: powered on has
        // to mean running, or a machine started by a link sits frozen until
        // somebody happens to click.
        console.log("Audio context suspended, free-running until first gesture");
        this.setFreeRun(true);
        this.setupAutoResumeAudio();
        this.running = true;
        return;
      }

      await this.initAudioNodes();
    } catch (error) {
      console.error("Failed to start audio driver:", error);
      // No audio at all on this browser. The machine still has to run.
      this.setFreeRun(true);
      this.running = true;
    }
  }

  /**
   * Ask the Worker to start or stop pacing the emulation from its own timer.
   *
   * @param {boolean} enabled
   */
  setFreeRun(enabled) {
    if (this.onFreeRunChange) this.onFreeRunChange(enabled);
  }

  async initAudioNodes() {
    // Audio is about to pace the machine, so the stand-in timer must go — two
    // clocks driving the same emulation would run it at roughly double speed.
    this.setFreeRun(false);

    this.gainNode = this.audioContext.createGain();
    this.gainNode.connect(this.audioContext.destination);
    this.gainNode.gain.value = this.muted ? 0 : this.volume;

    if (this.useWorklet) {
      await this.startWithWorklet();
    } else {
      this.startWithScriptProcessor();
    }

    this.running = true;
    console.log("Audio driver started (relay mode)");
  }

  setupAutoResumeAudio() {
    const resumeAudio = async () => {
      if (this.audioContext && this.audioContext.state === "suspended") {
        try {
          await this.audioContext.resume();
          console.log("Audio context resumed");
          await this.initAudioNodes();
        } catch (e) {
          console.error("Failed to resume audio context:", e);
        }
      }
      document.removeEventListener("click", resumeAudio);
      document.removeEventListener("keydown", resumeAudio);
    };

    document.addEventListener("click", resumeAudio, { once: true });
    document.addEventListener("keydown", resumeAudio, { once: true });
  }

  async startWithWorklet() {
    const workletPath = import.meta.env.DEV
      ? "/src/js/audio/audio-worklet.js"
      : `/audio-worklet.js?v=${VERSION}`;
    await this.audioContext.audioWorklet.addModule(workletPath);

    this.workletNode = new AudioWorkletNode(
      this.audioContext,
      "apple-audio-processor",
      {
        numberOfInputs: 0,
        numberOfOutputs: 1,
        outputChannelCount: [2],
      },
    );

    // Audio-driven timing: AudioWorklet requests samples when buffer is low.
    // We forward the request to the Worker, which generates and posts back.
    this.workletNode.port.onmessage = (event) => {
      if (event.data.type === "requestSamples" && this.onSamplesRequested) {
        this.onSamplesRequested(event.data.count);
      }
    };

    // Hand over the shared ring before starting, so the very first process()
    // call already reads from it rather than the postMessage fallback.
    if (this.sharedAudioBuffer) {
      this.workletNode.port.postMessage({
        type: "shared-audio",
        buffer: this.sharedAudioBuffer,
      });
    }

    this.workletNode.connect(this.gainNode);
    this.workletNode.port.postMessage({ type: "start" });
  }

  /**
   * Give the driver a SharedArrayBuffer ring to use instead of relaying sample
   * data through postMessage. Must be called before start().
   */
  setSharedAudioBuffer(buffer) {
    this.sharedAudioBuffer = buffer;
  }

  startWithScriptProcessor() {
    this.scriptProcessor = this.audioContext.createScriptProcessor(4096, 0, 2);
    // In relay mode, ScriptProcessor pulls from our internal buffer
    this._spBuffer = new Float32Array(0);
    this._spReadPos = 0;

    this.scriptProcessor.onaudioprocess = (event) => {
      const leftChannel = event.outputBuffer.getChannelData(0);
      const rightChannel = event.outputBuffer.getChannelData(1);
      const frames = leftChannel.length;

      for (let i = 0; i < frames; i++) {
        if (this._spReadPos + 1 < this._spBuffer.length) {
          leftChannel[i] = this._spBuffer[this._spReadPos++];
          rightChannel[i] = this._spBuffer[this._spReadPos++];
        } else {
          leftChannel[i] = 0;
          rightChannel[i] = 0;
        }
      }
    };

    this.scriptProcessor.connect(this.gainNode);
  }

  /**
   * Relay audio samples received from the Worker to the AudioWorklet.
   * @param {Float32Array} samples - Interleaved stereo samples
   */
  relaySamples(samples) {
    // In shared mode the Worker writes straight into the ring the worklet
    // reads; nothing should be arriving here at all.
    if (this.sharedAudioBuffer) return;

    if (this.workletNode && this.workletNode.port) {
      // Transfer rather than clone — this is the fallback path, but there is
      // no reason for it to copy 12KB of audio on every refill either.
      this.workletNode.port.postMessage({
        type: "samples",
        data: samples,
      }, [samples.buffer]);
    } else if (this.scriptProcessor) {
      // Append to ScriptProcessor buffer
      const newBuf = new Float32Array(this._spBuffer.length - this._spReadPos + samples.length);
      newBuf.set(this._spBuffer.subarray(this._spReadPos));
      newBuf.set(samples, this._spBuffer.length - this._spReadPos);
      this._spBuffer = newBuf;
      this._spReadPos = 0;
    }
  }

  stop() {
    if (!this.running) return;
    this.running = false;

    // The machine is being powered off; nothing should keep driving it.
    this.setFreeRun(false);

    if (this.workletNode) {
      try {
        this.workletNode.port.postMessage({ type: "stop" });
        this.workletNode.disconnect();
      } catch (e) {
        // Ignore errors during cleanup
      }
      this.workletNode = null;
    }

    if (this.scriptProcessor) {
      try {
        this.scriptProcessor.disconnect();
      } catch (e) {
        // Ignore errors during cleanup
      }
      this.scriptProcessor = null;
    }

    if (this.audioContext) {
      try {
        this.audioContext.close();
      } catch (e) {
        // Ignore errors during cleanup
      }
      this.audioContext = null;
    }

    console.log("Audio driver stopped");
  }

  setSpeed(speed) {
    this.speed = speed;
  }

  toggleMute() {
    this.muted = !this.muted;
    if (this.gainNode) {
      this.gainNode.gain.value = this.muted ? 0 : this.volume;
    }
    this.wasmModule._setAudioMuted(this.muted);
    this.saveMuted();
  }

  isMuted() {
    return this.muted;
  }

  mute() {
    this.muted = true;
    if (this.gainNode) {
      this.gainNode.gain.value = 0;
    }
    this.wasmModule._setAudioMuted(true);
    this.saveMuted();
  }

  unmute() {
    this.muted = false;
    if (this.gainNode) {
      this.gainNode.gain.value = this.volume;
    }
    this.wasmModule._setAudioMuted(false);
    this.saveMuted();
  }

  loadMuted() {
    try {
      return localStorage.getItem('a2e-muted') === 'true';
    } catch (e) {
      // Ignore localStorage errors
    }
    return false;
  }

  saveMuted() {
    try {
      localStorage.setItem('a2e-muted', this.muted.toString());
    } catch (e) {
      // Ignore localStorage errors
    }
  }

  getVolume() {
    return this.volume;
  }

  setVolume(volume) {
    this.volume = Math.max(0, Math.min(1, volume));
    if (this.gainNode) {
      this.gainNode.gain.value = this.muted ? 0 : this.volume;
    }
    this.wasmModule._setAudioVolume(this.volume);
    this.saveVolume();
  }

  loadVolume() {
    try {
      const saved = localStorage.getItem('a2e-volume');
      if (saved !== null) {
        const vol = parseFloat(saved);
        if (!isNaN(vol) && vol >= 0 && vol <= 1) {
          return vol;
        }
      }
    } catch (e) {
      // Ignore localStorage errors
    }
    return DEFAULT_VOLUME;
  }

  saveVolume() {
    try {
      localStorage.setItem('a2e-volume', this.volume.toString());
    } catch (e) {
      // Ignore localStorage errors
    }
  }

}
